import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Sidebar from "@/components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tutorial - Next",
  description: "Generated by Harshit",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-screen overflow-hidden flex text-white">
          <div className="h-screen w-1/6 bg-slate-900">
            <Sidebar />
          </div>
          <div className="bg-slate-800 w-full h-screen overflow-hidden overflow-x-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
